"""Refactor TestCase: remove config, support multiple workflows with file upload per workflow

Revision ID: 0e10b5944e02
Revises: a00d64027d1f
Create Date: 2025-05-23 21:23:24.233513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e10b5944e02'
down_revision = 'a00d64027d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('sample_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_column('config')
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('config', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'workflow', ['workflow_id'], ['id'])

    op.drop_table('testcase_workflow')
    # ### end Alembic commands ###
