"""Add active field to FileType

Revision ID: 23ea86c66706
Revises: b73be0638e49
Create Date: 2025-05-06 22:31:50.956935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ea86c66706'
down_revision = 'b73be0638e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_type', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
