"""Add schema field to Configuration

Revision ID: 35a4d28232a1
Revises: c355b81aa52b
Create Date: 2025-05-06 21:05:01.417320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a4d28232a1'
down_revision = 'c355b81aa52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('schema')

    # ### end Alembic commands ###
