"""Add file_mode to FileType

Revision ID: 4c4360de8634
Revises: f08e10b9a503
Create Date: 2025-05-19 03:56:19.565602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4360de8634'
down_revision = 'f08e10b9a503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_mode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_type', schema=None) as batch_op:
        batch_op.drop_column('file_mode')
        batch_op.drop_column('extraction_rules')

    # ### end Alembic commands ###
