"""add converter_config table

Revision ID: 634aca4653aa
Revises: 99ab58e1c17a
Create Date: 2025-05-07 02:08:52.463652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634aca4653aa'
down_revision = '99ab58e1c17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converter_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('converter_config')
    # ### end Alembic commands ###
