"""Add AuditLog model

Revision ID: 99ab58e1c17a
Revises: 23ea86c66706
Create Date: 2025-05-06 22:35:02.835137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ab58e1c17a'
down_revision = '23ea86c66706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('filetype', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
